version: "3.8"

services:
  php:
    container_name: app-php
    build: .
    volumes:
      - ./:/var/www/html:delegated
      - ./.docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    command: bash -c "composer install --dev && php bin/console doctrine:migrations:migrate --no-interaction && /usr/bin/supervisord -n"
    depends_on:
      - postgres
      - valkey
    networks:
      - app-net

  nginx:
    container_name: app-nginx
    image: nginx:1.27
    volumes:
      - ./:/var/www/html:delegated
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - ${NGINX_PORT}:80
    networks:
      - app-net

  postgres:
    container_name: app-postgres
    image: postgres:16.3
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD="trust"
    volumes:
      - app-postgres-vol:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - app-net

  valkey:
    container_name: app-valkey
    image: valkey/valkey:7.2
    volumes:
      - app-valkey-vol:/data
    ports:
      - ${VALKEY_PORT}:6379
    networks:
      - app-net

networks:
  app-net:

volumes:
  app-postgres-vol:
  app-valkey-vol:
